import { useLogger } from './useLogger';
import { useYtdlp } from './useYtdlp';

import { importModule } from '../_func';

type TUseYoutube = {
    ytdlpPath: string;
    videoId: string;
    dest: string;
    debug?: boolean;
    tempDir: string;
    ffmpegConfig: {
        ffmpegDir: string;
        ffmpegPath: string;
        ffmpegProbePath: string;
        ffmpegPlayPath: string;
    };
};

export const useYoutube = async ({
    debug = false,
    ytdlpPath,
    videoId,
    dest,
    tempDir,
    ffmpegConfig,
}: TUseYoutube): Promise<[Error | null, boolean | null]> => {
    const logger = useLogger(debug);
    logger.log(`Downloading video: ${videoId} to: ${dest}`);

    const fs: any = await importModule('fs');
    const path: any = await importModule('path');
    const puppeteer: any = await importModule('puppeteer');

    const videoUrl = `https://www.youtube.com/watch?v=${videoId}`;
    const COOKIE_FILE_PATH = path.join(path.dirname(ytdlpPath), 'cookies.txt');

    // Netscape cookie format helper
    const toNetscape = (cookies: any = []): string => {
        const header = [
            '# Netscape HTTP Cookie File',
            '# https://curl.se/docs/http-cookies.html',
            '# This file was generated by Puppeteer',
            '',
        ].join('\n');

        const lines = cookies.map((c: any) => {
            const domain = c.domain.startsWith('.') ? c.domain : `.${c.domain}`;
            const flag = 'TRUE';
            const pathVal = c.path || '/';
            const secure = c.secure ? 'TRUE' : 'FALSE';
            const expires = c.expires
                ? Math.floor(c.expires)
                : Math.floor(Date.now() / 1000) + 3600 * 24 * 365;
            const name = c.name;
            const value = c.value;

            return [domain, flag, pathVal, secure, expires, name, value].join('\t');
        });

        return header + '\n' + lines.join('\n') + '\n';
    };

    // 檢查是否有 cookies.txt，沒有就啟動 puppeteer 登入一次 (10 分鐘內有效)
    const setupCookies = async (): Promise<void> => {
        const USER_DATA_DIR = path.join(path.dirname(ytdlpPath), 'chrome-profile');
        if (!fs.existsSync(USER_DATA_DIR)) {
            fs.mkdirSync(USER_DATA_DIR, { recursive: true }, 777);
        }
        if (fs.existsSync(COOKIE_FILE_PATH)) {
            const timeout = 10 * 60 * 1000; // 10 分鐘
            const stat = fs.statSync(COOKIE_FILE_PATH);
            if (stat.mtimeMs + timeout > Date.now()) {
                logger.log('Using existing cookies.txt');
                return;
            }
        }

        console.log('Launching Chrome…');

        const browser = await puppeteer.launch({
            headless: false, // 必須 false
            userDataDir: USER_DATA_DIR, // 關鍵
            defaultViewport: null,
            args: ['--disable-blink-features=AutomationControlled'],
        });

        const page = await browser.newPage();
        await page.goto('https://www.youtube.com', {
            waitUntil: 'networkidle2',
        });

        console.log('If not logged in, please log in manually.');
        console.log('Waiting 30 seconds…');

        // 給你手動登入時間（第一次）
        await new Promise((r) => setTimeout(r, 30_000));

        const cookies = await page.cookies();

        const ytCookies = cookies.filter((c: any) => {
            return c.domain.includes('youtube.com') || c.domain.includes('google.com');
        });

        if (ytCookies.length === 0) {
            console.error('No YouTube cookies found. Are you logged in?');
            process.exit(1);
        }

        const content = toNetscape(ytCookies);
        fs.writeFileSync(COOKIE_FILE_PATH, content, { encoding: 'utf8' });

        console.log(`cookies.txt written to ${COOKIE_FILE_PATH}`);
        console.log(`Cookies count: ${ytCookies.length}`);

        await browser.close();
    };

    await setupCookies();

    const cmdArr = [
        `${ytdlpPath}`,
        '-f "bv*[vcodec^=avc1][acodec^=mp4a][height<=1080]/ba/b"',
        '--js-runtimes node',
        `${videoUrl}`,
        `-o "${tempDir}/%(id)s.%(ext)s"`,
        `--cookies ${COOKIE_FILE_PATH}`,
        ffmpegConfig.ffmpegDir ? `--ffmpeg-location "${ffmpegConfig.ffmpegDir}"` : '',
    ];

    return useYtdlp({
        debug,
        command: cmdArr.join(' '),
        dest,
        tempDir,
        ffmpegConfig,
    });
};
